name: "Setup Genesys Cloud Tools"
description: "Installs Archy and the Genesys Cloud CLI"
runs:
  using: "composite"
  steps:
    - run: |
        mkdir archy
        cd archy
        wget -q https://sdk-cdn.mypurecloud.com/archy/latest/archy-linux.zip
        unzip archy-linux.zip
        . archy version                            
        export PATH=$PATH:$GITHUB_WORKSPACE/archy
        cd ..
        pwd
        archy version
      shell: bash
