name: "Setup Genesys Cloud Tools"
on:
  workflow_call:
jobs:
  Archy:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - run: |
          mkdir archy
          cd archy
          wget -q https://sdk-cdn.mypurecloud.com/archy/latest/archy-linux.zip
          unzip archy-linux.zip
          . archy version                            
          export PATH=$PATH: pratyusha-deekshit/terraform_CLI/archy
          cd ..
          pwd
          archy version
        shell: bash
